### ISSUE TITLE
Erstes Diagrammm

### ISSUE THREAD

**Issue by jakobbraun** [philipphoberg/teleTunes#10]
Frontend:
- Start und Ende auswählen
- Ajax anfrage
- Liniendiagramm

Backend:
- für jeden Tag downloads für alle kurse gruppiert (Pro tag 1 zahl)

**Comment by youri-k** [comment]
Also das Backend kann das jetzt erstmal für alle verfügbaren Tage, aber das mit Start und Ende kann man ja noch adden

**Comment by youri-k** [comment]
Jetzt gibts auch die Möglichkeit nen Start- und Enddatum anzugeben
